### ISSUE TITLE
Support other objects than image

### ISSUE THREAD

**Issue by hadim** [InsightSoftwareConsortium/itkwidgets#112]
It would be nice to be able to display 3D objects such as in this example among others: https://kitware.github.io/vtk-js/examples/SphereMapper.html

**Comment by thewtex** [comment]
:+1: This is on the agenda!

**Comment by WesleyTheGeolien** [comment]
I'd be keen on this functionality and able to help to, The viewer class seems intimatly linked to the ITKImage would there be a way to abstract this? I've had a quick look at creating just the vtk.js viewer without passing the data through. Then the next steps I believe would be to workout how to serialize some of the other VTK classes. @thewtex is this along the right lines?

**Comment by thewtex** [comment]
@WesleyTheGeolien fantastic! The help would be appreciated!

Yes, your assessment is correct: the next steps are serializing the data for consumption in vtk.js.

If you want to start pushing it forward, functions in JavaScript to serialize / deserialize the itk.js [`Mesh`](https://insightsoftwareconsortium.github.io/itk-js/api/Mesh.html) data structure would help. We will use this to efficiently (in compressed form) transmit the data from the kernel to the browser. There are not any JavaScript tests, but this could be a good time to start :-).

**Comment by WesleyTheGeolien** [comment]
Sounds great I'll try and take a look in the next few weeks and reach out if / when I need help

**Comment by thewtex** [comment]
An update: we will store a vtk.js [`PolyData`](https://kitware.github.io/vtk-js/docs/structures_PolyData.html) instead of an itk.js Mesh client-side.

**Comment by thewtex** [comment]
We now have support for geometry / meshes and point sets -- please see the examples, and create an issue if anything is missing that you need :-).
