### ISSUE TITLE
Error creating widget for line_profile

### ISSUE THREAD

**Issue by carluri** [InsightSoftwareConsortium/itkwidgets#128]
Hello,

I've been using itkwidgets 0.15.2.  The `view` widget has been working fine for me in the jupyter lab.  However, when I try to use the `line_profile` widget I get the message "Error displaying widget" but a line plot is displayed as shown

![image](https://user-images.githubusercontent.com/3673343/50701650-4b8d2b80-1003-11e9-9d85-c169d4623507.png)

However, if I execute that cell again I only get the "Error displaying widget" message without any plots.

Anyone knows how to solve this?

**Comment by thewtex** [comment]
Hi @carluri ,

Is there any error information in the terminal console or in the browser console? To view the browser console, press "Ctrl + Shift + I" and click the "Console".
