### ISSUE TITLE
Interactive sliders to update ITK widget do not work on Firefox

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/itkwidgets#136]
When integrating an itk-jupyter-widget viewer with an interactive slider in a Python notebook and visualizing it with Firefox, the viewer does not refresh when the slider is moved.

To reproduce the error, use [this binder](https://mybinder.org/v2/gh/InsightSoftwareConsortium/ITKSplitComponents/master?filepath=examples%2FITKSplitComponents.ipynb).

Firefox console log:
[itkWidgetErrorWithSliderOnFirefox.txt](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/files/3065053/itkWidgetErrorWithSliderOnFirefox.txt)

**Comment by thewtex** [comment]
Testing this notebook on recent versions:

https://mybinder.org/v2/gh/InsightSoftwareConsortium/itkwidgets/master?urlpath=lab/tree/examples/InteractiveParameterExploration.ipynb

this appears to have been addressed.
