### ISSUE TITLE
ship with discontinous colormaps/LUTs for object label inspection

### ISSUE THREAD

**Issue by VolkerH** [InsightSoftwareConsortium/itkwidgets#140]
The default installation comes with a range of colormaps/LUTs that all seem to be optimized towards having some sort of visual continuity. 
Sometimes it is very useful to have a discontinuous colormap, where neighbouring grey values have very distinct colors, e.g. when one wants to inspect object labels for connected components (often objects that are close together have similar labels). A suitable colormap would for example be glasbey.

**Comment by VolkerH** [comment]
Just to illustrate. Here, connected objects have been split with a watershed. It is very hard to see whether they were actually split.

![image](https://user-images.githubusercontent.com/2210044/57840499-147a2280-780c-11e9-975d-4ab92bc23047.png)

**Comment by thewtex** [comment]
@VolkerH thanks for the report -- good idea.

We are adding support for segmentation surfaces, too -- the color sequences will be useful there, too.

@jourdain @jcfr @floryst any ideas / suggestions / tips on adding using continuous colormaps in vtk.js and bringing in the standard Slicer sequence and Glasbey?

**Comment by jourdain** [comment]
@martinken

**Comment by floryst** [comment]
Would using categorical colormaps help? Otherwise, we could manually construct colormaps with a sharpness of 1 (no interpolation between adjacent colors).

I looked at vtkColorTransferFunction, and we currently do not (yet) support loading preset categorical colormaps or preset colormaps that specify a sharpness other than 0. That should be a pretty easy addition though.

**Comment by VolkerH** [comment]
I don't know what the exact definition of a categorial colormap is. 

However, sharpness of 1 (no interpolation) and a large percpetual difference between adjacent colors are important. With such colormaps it is probably advised to lock down interpolation to nearest neighbour as otherwise boundary voxels (e.g. between an object with label 20 and a background of 0) might be interpolated to an intermediate value which then appear to represent  a very different object (label 10).

However, I'm not sure whether linking the choice of interpolation option to the colormap is a good idea.

**Comment by thewtex** [comment]
We now have support for this categorical colormaps / LUTs! :tada: 

![LabelMapLookupTables](https://user-images.githubusercontent.com/25432/85350786-0e0aaf80-b4d0-11ea-8cdd-0da4a4acffd1.gif)

https://mybinder.org/v2/gh/InsightSoftwareConsortium/itkwidgets/master?urlpath=lab/tree/examples%2FLabelMaps.ipynb

A `lut` trait / `view` argument is added in https://github.com/InsightSoftwareConsortium/itkwidgets/pull/336

**Comment by VolkerH** [comment]
Thank you !
