### ISSUE TITLE
Support appending geometry and point sets after widget creation

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itkwidgets#166]
@banesullivan there will be some refactoring before this is supported properly, but it is coming.

**Comment by banesullivan** [comment]
ref #154

**Comment by thewtex** [comment]
@banesullivan #201 brought it a major JavaScript refactoring to address this. If any issues persists, please open an issue :pray: - thanks!

**Comment by banesullivan** [comment]
@thewtex, I'm trying to leverage #201 to implement this and cannot quite figure it out. How would I append geometries to the Viewer class? This is what I have so far..

```py
import pyvista as pv
from pyvista import examples

from itkwidgets import view, Viewer
from itkwidgets._transform_types import to_point_set, to_geometry, to_itk_image

mesh = examples.download_st_helens()
warp = mesh.warp_by_scalar()

plotter = Viewer()
plotter.geometries = [mesh,]
plotter.geometries.append(to_geometry(warp))
plotter
```

which doesn't add bothe meshes to the scene

**Comment by thewtex** [comment]
@banesullivan does

```
plotter.geometries = [mesh,]
plotter.geometries = ploter.geometries + [to_geometry(warp)]
```

work?
