### ISSUE TITLE
camera control

### ISSUE THREAD

**Issue by fcollman** [InsightSoftwareConsortium/itkwidgets#194]
could you point me to where you would control the camera position programatically on these widgets?  i have very large meshes and would like to point the camera at parts of them with code..

**Comment by thewtex** [comment]
An initial implementation was added in #202 .

Still todo:

- [ ] Support setting with a `vtkCamera` instance
- [ ] Add the convenience methods for manipulating the camera

**Comment by thewtex** [comment]
vtkCamera support added in #369
