### ISSUE TITLE
Add a color legend or color bar to the view

### ISSUE THREAD

**Issue by wigging** [InsightSoftwareConsortium/itkwidgets#196]
Viewing VTK files in the notebook does not display the scale of values associated with the color map. This is typically displayed as a color bar or color legend. The current version of itkwidgets does not appear to have this feature. See this ParaView article for an example of a color legend: https://blog.kitware.com/using-the-color-map-editor-in-paraview-the-annotations/.

**Comment by thewtex** [comment]
Following @jourdain 's tips, we now have a nice color map range by default in the UI with #201 :tada:  :

![image](https://user-images.githubusercontent.com/25432/64502017-dc529000-d291-11e9-9842-957a79c2c0e8.png)

This shows the colormap, but also the minimum and maximum values that are mapped. Better yet, these values can be interactively changed to adjust the range :rabbit: .

For creating color legends for figures used in publications, matplotlib could be used. We already have some matplotlib colormaps, but with #186, we will be able to use any.
