### ISSUE TITLE
browser error

### ISSUE THREAD

**Issue by jxchen01** [InsightSoftwareConsortium/itkwidgets#207]
When I use view(im), the image cannot be displayed. I got the following error message. Any idea? 

load_extensions Arguments(2)
main.min.js:47981 Loaded moment locale en
main.min.js:24063 Loading extension: itkwidgets/extension
main.min.js:38291 Session: kernel_created (c994d5a3-db15-4732-a3eb-a1216a90c34b)
main.min.js:37449 Starting WebSockets: ws://localhost:8888/api/kernels/3c95e76d-5f0e-45f2-aab6-5267b425f85e
main.min.js:24063 Loading extension: nb_conda/main
:8888/nbextensions/widgets/notebook/js/extension.js?v=20190926141818:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.min.js:50709 Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
(anonymous) @ main.min.js:50709
main.min.js:37093 Kernel: kernel_connected (3c95e76d-5f0e-45f2-aab6-5267b425f85e)
main.min.js:37093 Kernel: kernel_ready (3c95e76d-5f0e-45f2-aab6-5267b425f85e)
main.min.js:24956 Could not open comm  --  Error: Class jupyter.widget not found in registry 
    at main.min.js:24920
    at new Promise (<anonymous>)
    at Object.load_class (main.min.js:24905)
    at CommManager.comm_open (main.min.js:36730)
    at i (main.min.js:2)
    at Kernel._handle_iopub_message (main.min.js:38211)
    at Kernel._finish_ws_message (main.min.js:38003)
    at main.min.js:37994
(anonymous) @ main.min.js:24956
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:24956 Could not open comm  --  Error: Class jupyter.widget not found in registry 
    at main.min.js:24920
    at new Promise (<anonymous>)
    at Object.load_class (main.min.js:24905)
    at CommManager.comm_open (main.min.js:36730)
    at i (main.min.js:2)
    at Kernel._handle_iopub_message (main.min.js:38211)
    at Kernel._finish_ws_message (main.min.js:38003)
    at main.min.js:37994
(anonymous) @ main.min.js:24956
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995
main.min.js:37995 Couldn't process kernel message WrappedError
(anonymous) @ main.min.js:37995

**Comment by jxchen01** [comment]
itkwidgets version = 0.21.1
browser is Chrome
OS: Ubuntu
python: 3.6

**Comment by thewtex** [comment]
> Please install widgetsnbextension or ipywidgets 4.0

How was it installed? Is this with JupyterLab or the Jupyter Notebook?

**Comment by thewtex** [comment]
> Widgets are not available. Please install widgetsnbextension or ipywidgets 4.0

Looks to be an installation issue. Please see the README for installation instructions.
