### ISSUE TITLE
Error: Can't resolve 'es6-promise/auto'

### ISSUE THREAD

**Issue by jhgoebbert** [InsightSoftwareConsortium/itkwidgets#216]
If itkwidget is installed as jupyterlab extension with
```
jupyter labextension install itkwidgets@0.20.1
```
other extensions like jupyterlab-plotly@1.2.0 or dask-labextension@1.0.1 fail with the error
```
cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'es6-promise/auto' in '<jupyterroot>/share/jupyter/lab/staging/build'
```

Looking at the install directory it seems as if es6-promise is installed in version 3.0, which does not include "auto". But other extensions cannot upgrade es6-promise for some reason.

**Comment by thewtex** [comment]
@jhgoebbert thanks for the report.

 It looks like we have the dependency chain:

`itkwidgets` -> `vtk-js` -> `jszip` -> `es6-promise`

I update `jszip` in `vtk-js` and see where that gets us.

**Comment by thewtex** [comment]
@jhgoebbert 0.22.0 is released, and `es6-promise` no longer exists in *js/package-lock.json* -- please give it a try, and re-open if the issue still persists. Thanks!

**Comment by consideRatio** [comment]
This exact error surfaced for me while rebuilding a Dockerfile including itkwidgets the conda package and the jupyterlab extension. The Dockerfile doesn't pin pip/conda packages or jupyterlab extensions, so I assume one update of these packages made the issue surface.

Now I wonder to myself how I can debug this further, and I'm looking for advice on that.

@thewtex you concluded to have a npm dependency chain of `itkwidgets -> vtk-js -> jszip -> es6-promise` before, how did you conclude that? Are there some nice tools to debug npm package dependency trees?

**Comment by thewtex** [comment]
@consideRatio there may be better ways to visualize the npm package dependencies, but I just manually go through the `package-lock.json` file found in the npm package (tarball). It is pretty straightforward.
