### ISSUE TITLE
0.20.1 - Performance regression introduced somewhere

### ISSUE THREAD

**Issue by consideRatio** [InsightSoftwareConsortium/itkwidgets#217]
Thanks for your work on this everybody involved!

---

It seems like there has been a significant performance regression, I sadly cannot contribute much to pinpointing when/where it was introduced at the moment though.

In my current experience, the initial loading of the demo brain takes about 30-40 seconds where it previously took about 5. Currently, any movement to the camera is now extremely burdened with multi-second lag where it was previously fluent. Hovering the mouse over the brain also seem to trigger re-rendering without any change to the view.

**Comment by thewtex** [comment]
@consideRatio thanks for the feedback. :bookmark: 

More details may help -- what is the browser, operating system, graphics card, Python, Jupyter or JupyterLab version?

**Comment by consideRatio** [comment]
I found that theexperience can be reproduced this repository's [brain demo on mybinder.org](https://mybinder.org/v2/gh/InsightSoftwareConsortium/itkwidgets/master?filepath=examples%2F3DImage.ipynb) for me, using Chrome on Ubuntu 18.04.

On my own setup as reported, I was running Chrome on Ubuntu 18.04, unknown laptop graphics card of modern laptop but the same as I've done before with better performance, conda's python package itkwidges==0.21.1, and the itkwidgets npm package==0.20.1 (latest of both). Also, the following versions where reported relating to Jupyter:

```
jovyan:~$ jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
^[[Aipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
```

This is from the README.md, it shows what I've loved to experience before.
![](https://camo.githubusercontent.com/369b261f93c95bb3647ada9c4303f763d1fc23ee/68747470733a2f2f7468756d62732e6766796361742e636f6d2f53687946656c696e65426565746c652d73697a655f726573747269637465642e676966)

**Comment by consideRatio** [comment]
Rotate=false was still greatly different from the past experience (like in the GIF of the readme)

**Comment by thewtex** [comment]
Does the behavior reproduce in Firefox?

**Comment by thewtex** [comment]
Re: https://github.com/Kitware/paraview-glance/issues/270 , if you open up the browser developer Console (Ctrl + Shift + i ), and enter

```
> window.devicePixelRatio
```

what is returned?

**Comment by consideRatio** [comment]
Firefox was perfect! Everything worked great on mybinder.org with firefox but not with chrome. I set my zoom to 100% so the window.devicePixelRatio returned 1. I did this before I ran the code cells to load itkwidgets etc for the first time.

Chrome was bad on my Ubuntu 18.04, where Chrome had the version 76.0.3809.132 (Official Build) (64-bit).

This is the Chrome experience, 
![chrome](https://user-images.githubusercontent.com/3837114/67810391-ce074000-fa9a-11e9-841d-ba06592283a6.gif)

This is the firefox experience:
![firefox](https://user-images.githubusercontent.com/3837114/67810555-19215300-fa9b-11e9-8297-680b997b9478.gif)

**Comment by thewtex** [comment]
@consideRatio I love the GIFs -- very helpful! 

I also have Ubuntu 18.04, but I am not seeing the same behavior.  I have version 78.0.3904.70 -- if Chrome is upgraded, does that address the issue?

**Comment by consideRatio** [comment]
@thewtex i upgraded to Version 78.0.3904.70 (Official Build) (64-bit) and the issue persist, even in incognito and extensions disabled.

**Comment by thewtex** [comment]
@consideRatio itkwidgets 0.22.0 was just released. This version bumps vtk.js and contain rendering fixes. While I am not certain of the root cause of the behavior observed, this new version is worth a try.

**Comment by consideRatio** [comment]
Nice! I checked again and verified usage of new versions. I think the performance issue has gone away. But the visual difference in quality between chrome and firefox in the GIF animations above remains.

**Comment by consideRatio** [comment]
I'm no longer able to reproduce this error! ;) Closing!

**Comment by thewtex** [comment]
@consideRatio thanks for the follow-up!

I am working towards dynamically updating the resolution based on hardware and software capabilities so everyone gets an optimal rendering and interactivity experience.

**Comment by thewtex** [comment]
Just a note: #338 may be related.
