### ISSUE TITLE
View does not appear in Safari on macOS Catalina

### ISSUE THREAD

**Issue by wigging** [InsightSoftwareConsortium/itkwidgets#222]
When using Safari on a Mac, the itkwidget view does not display in a Jupyter notebook. I ran the same notebook in Firefox and the view appears as it should. Below is my code example:

```python
# View the VTK file using `itkwidgets`
file_name = 'unrolled_cell.vtk'

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName(file_name)
reader.Update()

geometryFilter = vtk.vtkGeometryFilter()
geometryFilter.SetInputData(reader.GetOutput())
geometryFilter.Update()
unrolled_cell = geometryFilter.GetOutput()

itkwidgets.view(geometries=unrolled_cell)
```

Here is my current setup:
- macOS Catalina v10.15
- Safari v13.0.2
- Python v3.7.3
- itkwidgets v0.22.0
- jupyterlab v1.0.4

Is itkwidgets not compatible with Safari on macOS Catalina?

**Comment by wigging** [comment]
The issue I had with the view not appearing seems to be fixed after I updated to macOS v10.15.1 and Safari v13.0.3. Can anyone else verify this?

**Comment by thewtex** [comment]
@wigging thanks for the report -- if this was addressed by macOS v10.15.1, should we close the issue?

**Comment by wigging** [comment]
Closed since the latest version of Safari and macOS seem to have fixed the problem.

**Comment by thewtex** [comment]
@wigging thanks for the update :+1:
