### ISSUE TITLE
VisualizeImageLabels

### ISSUE THREAD

**Issue by dani-lbnl** [InsightSoftwareConsortium/itkwidgets#225]
At itkwidgets/examples/VisualizeImageLabels.ipynb, this is how to do in skimage:
from skimage import io, filters, measure
image = io.imread(file_name)
img2 = filters.gaussian(image)
t=filters.threshold_isodata(img2)
img3 = img2>t
img4 = measure.label(img3)
image_itk = itk.GetImageFromArray(img4.astype(np.uint16))
view(image_itk)

**Comment by thewtex** [comment]
Excellent! :+1:

**Comment by thewtex** [comment]
Added in #360
