### ISSUE TITLE
Binder Notebooks unable to import vtkOpenGLKitPython

### ISSUE THREAD

**Issue by SimonBiggs** [InsightSoftwareConsortium/itkwidgets#230]
There are a range of binder notebooks which receive the following error:

```
/srv/conda/envs/notebook/lib/python3.6/site-packages/vtk/vtkOpenGLKit.py in <module>
      7     # during build and testing, the modules will be elsewhere,
      8     # e.g. in lib directory or Release/Debug config directories
----> 9     from vtkOpenGLKitPython import *

ModuleNotFoundError: No module named 'vtkOpenGLKitPython'
```

**Comment by thewtex** [comment]
@SimonBiggs which notebooks?

**Comment by thewtex** [comment]
Running the VTK-dependent notebooks on Binder has issues due to VTK Python packaging and execution in the Binder OpenGL environment -- that is why they are currently excluded from the Binder links.

@mathstuf @demarle @jcfr
