### ISSUE TITLE
Add preferred citation information

### ISSUE THREAD

**Issue by munkm** [InsightSoftwareConsortium/itkwidgets#236]
I noticed an open issue in the ITK main repository for adding a citation section to the README (https://github.com/InsightSoftwareConsortium/ITK/issues/456) and links to the current DOIs on Zenodo. I'd like to cite itkwidgets as well -- what would be the best/preferred way to cite this particular software?

**Comment by thewtex** [comment]
@munkm thank you much such for opening this issue and for citing the software! :pray:

In the short term, we will add a Zenodo DOI -- will follow-up once that is ready. Please go ahead and use that.

In the longer term, we will create a JOSS paper and a paper in another academic journal.

@dana-lbnl

**Comment by thewtex** [comment]
@munkm we now have a Zenodo entry: https://zenodo.org/record/3603359

**Comment by munkm** [comment]
Thank you so much @thewtex! I really appreciate your quick turnaround. 

I'm looking forward to seeing your JOSS paper. 🎈 ✍️ 😎 Thanks for making such a cool tool.
