### ISSUE TITLE
geometry_opacities are passed to js widget yet not activated

### ISSUE THREAD

**Issue by OlegJakushkin** [InsightSoftwareConsortium/itkwidgets#262]
Before manual mouse slider move  **(_Bad_)**

![image](https://user-images.githubusercontent.com/2915361/72659041-a903d880-39ca-11ea-9e55-8a1bef2603af.png)

After insignificant mouse slider move **(_Desired_)**
![image](https://user-images.githubusercontent.com/2915361/72659055-d3ee2c80-39ca-11ea-93da-eeb83e61ca4c.png)

Code sample:
```
from itkwidgets import view
import pyvista
from pyvista import *

vol = pyvista.UnstructuredGrid('./u000000.vtu')
view(geometries=[vol.contour(), vol], geometry_opacities=[1, 0.25], slicing_planes=True)
```

[Datafile](https://github.com/InsightSoftwareConsortium/itkwidgets/files/4080001/u000000_rename.txt) (please rename to `u000000.vtu`)

I would like for the desired outcome to happen without manual slider movement (or for support of unstructured volumes rendering in-browser with something like `view(vol)`).

BTW works for one argument... so definitely a bug.
![image](https://user-images.githubusercontent.com/2915361/72659170-9db1ac80-39cc-11ea-8492-1257d4b3095c.png)

**Comment by thewtex** [comment]
@OlegJakushkin thank you for the report, detailed screenshots, code, and data. I was able to reproduce the issue, and it is addressed by #265
