### ISSUE TITLE
JupyterLab extension: new release for JupyterLab 2 compatibility

### ISSUE THREAD

**Issue by consideRatio** [InsightSoftwareConsortium/itkwidgets#286]
To have full JupyterLab 2 support, we need to have JupyterLab 2 support in all the JupyterLab extensions suggested to be installed in this projects readme.

## JupyterLab 2 support
- @jupyter-widgets/jupyterlab-manager: OK
- [jupyter-matplotlib](https://github.com/matplotlib/ipympl): OK
- [jupyterlab-datawidgets](https://github.com/vidartf/ipydatawidgets): OK
- itkwidgets: needs a release [beyond 0.26.0](https://www.npmjs.com/package/itkwidgets)

Thanks for all your hard work on this project!

**Comment by thewtex** [comment]
@consideRatio thanks for issue -- I will generate 0.26.1 to include https://github.com/InsightSoftwareConsortium/itkwidgets/commit/d67a6fba8f14583360e2f8d28129851eed42268b
