### ISSUE TITLE
itkwidgets version 0.27.0 not rendering on Ubuntu 18 LTS

### ISSUE THREAD

**Issue by gattia** [InsightSoftwareConsortium/itkwidgets#293]
OS: Ubuntu 18.04.3 LTS
Server on google cloud
Conda environment running python 3.6.10
itkwidgets installed using conda install -c confa-forge

I was trying to view some meshes on a server using itkwidgets in a Jupiter notebook (not lab) and the renderings weren't working. No warnings, no errors, just nothing shows up after running the cell: 
```
from itkwidgets import view
view(geometries=[mesh])
```
Might be of interest to note that when the jupyter server is shutdown and you navigate to the page the space following the above cell (where the mesh/vtk js stuff should be) shows a broken link, so it thinks something should be there its just not showing it. 

I had previous servers that worked. I ended up downgrading to 0.26.1 to match another server and everything worked fine. Upgraded again to double-check and it fails to render.

Im happy with using 0.26.1, posting in case someone else has the same issue or there is something that should be fixed.

**Comment by thewtex** [comment]
@gattia thanks for the report. I'll investigate.

**Comment by abnowack** [comment]
Same issue, version, and behavior here on Windows 10

**Comment by theaboutbox** [comment]
I had the same problem on the mac. Downgrading fixed the issue. For what it's worth, I did see this in the jupyter-notebook logs:

`[I 09:57:02.359 NotebookApp] Kernel started: 08665294-b401-48ae-965d-ba27e4ba3412
[W 09:57:24.459 NotebookApp] 404 GET /nbextensions/itkwidgets/itk/Pipelines/ZstdDecompressWasm.wasm (::1) 13.27ms referer=http://localhost:8888/nbextensions/itkwidgets/itk/WebWorkers/Pipeline.worker.js`

**Comment by thewtex** [comment]
This should be addressed by:

https://github.com/InsightSoftwareConsortium/itkwidgets/commit/5bec6d7a25c991d224586cda93afe33a747bd7b5

We will release 0.27.2 with this fix, soon.

**Comment by thewtex** [comment]
Thanks again for the report.

This should be addressed in version 0.27.2, `pip install --upgrade itkwidgets` -- if not, please re-open. Thanks!
