### ISSUE TITLE
ITK Widgets not displaying in windows 7 machine

### ISSUE THREAD

**Issue by paulomontijo** [InsightSoftwareConsortium/itkwidgets#297]
Hello,

I'm trying to use the command view of itk widgets as follows:

`from itkwidgets import compare, view`
`compare(fixed_image, moving_image)`

And i get the following result:

![image](https://user-images.githubusercontent.com/43051367/81063386-f6ec1000-8ed7-11ea-87af-8e7128ca3796.png)

i.e. the images do not show, but the interface seems to be somehow working since the cmap and gradient opacity buttons are working.

I'm currently using a windows 7 machine and google chrome. In another windows 10 machine I can run the same code successfully.

Could anyone please help me?

**Comment by dani-lbnl** [comment]
which version are you using? can you post it? it's working fine under mac OS

**Comment by paulomontijo** [comment]
I'm usign itkwidgets 0.27.0

**Comment by thewtex** [comment]
This should be addressed by:

https://github.com/InsightSoftwareConsortium/itkwidgets/commit/5bec6d7a25c991d224586cda93afe33a747bd7b5

We will release 0.27.2 with this fix, soon.

**Comment by thewtex** [comment]
Thanks again for the report.

This should be addressed in version 0.27.2, `pip install --upgrade itkwidgets` -- if not, please re-open. Thanks!

**Comment by paulomontijo** [comment]
Hello, 

Thanks for the return.

I installed the new version of itkwidgets (0.27.2) and now I get the following error:

---> 15     import _ITKPyBasePython
     16 
     17 try:

ImportError: DLL load failed: The module couldn't be found.

**Comment by thewtex** [comment]
@paulomontijo what commands were used to install the packages?

**Comment by paulomontijo** [comment]
@thewtex,

on the machine I already had itkwidgets I used:

`pip install --upgrade itkwidgets`

on the other machine I used:

`pip install itkwidgets`

**Comment by thewtex** [comment]
@paulomontijo there were some recent updates that require an updated environment. Please try:

```
pip install --upgrade itkwidgets itk itk-meshtopolydata
```

If you had installed any other `itk-*` packages, they must also be upgraded.

**Comment by paulomontijo** [comment]
@thewtex i tried 

`pip install --upgrade itkwidgets itk itk-meshtopolydata`

and for other itk-* packages and the error persisted. After that I unistalled and reinstalled all itk packages and the error still persists:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-0a786189811f> in <module>
      1 from itkwidgets import compare, view
----> 2 compare(fixed_image, moving_image)

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkwidgets\widget_compare.py in compare(image1, image2, link_cmap, link_gradient_opacity, **viewer_kwargs)
     17     """
     18 
---> 19     viewer1 = Viewer(image=image1, **viewer_kwargs)
     20     # Collapse the second viewer's user interface by default.
     21     if 'ui_collapsed' not in viewer_kwargs:

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkwidgets\widget_viewer.py in __init__(self, **kwargs)
    297         self.observe(self._on_geometries_changed, ['geometries'])
    298 
--> 299         super(Viewer, self).__init__(**kwargs)
    300 
    301         if not self.image:

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\ipywidgets\widgets\widget.py in __init__(self, **kwargs)
    410         """Public constructor"""
    411         self._model_id = kwargs.pop('model_id', None)
--> 412         super(Widget, self).__init__(**kwargs)
    413 
    414         Widget._call_widget_constructed(self)

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\traitlets\traitlets.py in __init__(self, *args, **kwargs)
    995             for key, value in kwargs.items():
    996                 if self.has_trait(key):
--> 997                     setattr(self, key, value)
    998                 else:
    999                     # passthrough args that don't set traits to super

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\traitlets\traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\traitlets\traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\traitlets\traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkwidgets\trait_types.py in validate(self, obj, value)
     34         self._source_object = value
     35 
---> 36         image_from_array = to_itk_image(value)
     37         if image_from_array:
     38             return image_from_array

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkwidgets\_transform_types.py in to_itk_image(image_like)
    183     elif have_simpleitk and isinstance(image_like, sitk.Image):
    184         array = sitk.GetArrayViewFromImage(image_like)
--> 185         image_from_array = itk.image_view_from_array(array)
    186         image_from_array.SetSpacing(image_like.GetSpacing())
    187         image_from_array.SetOrigin(image_like.GetOrigin())

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkExtras.py in GetImageViewFromArray(arr, is_vector)
    297     """Get an ITK image view from a Python array.
    298     """
--> 299     return _GetImageFromArray(arr, "GetImageViewFromArray", is_vector)
    300 
    301 image_view_from_array = GetImageViewFromArray

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkExtras.py in _GetImageFromArray(arr, function, is_vector)
    268         raise ImportError('Numpy not available.')
    269     import itk
--> 270     PixelType = _get_itk_pixelid(arr)
    271     Dimension = arr.ndim
    272     ImageType = itk.Image[PixelType, Dimension]

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkExtras.py in _get_itk_pixelid(numpy_array_type)
    221                 numpy.float32:itk.F,
    222                 numpy.float64:itk.D,
--> 223                 numpy.complex64:itk.complex[itk.F],
    224                 numpy.complex128:itk.complex[itk.D]
    225                 }

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkLazy.py in __getattribute__(self, attr)
     50             module = self.__belong_lazy_attributes[attr]
     51             namespace = {}
---> 52             itkBase.LoadModule(module, namespace)
     53             self.loaded_lazy_modules.add(module)
     54             for k, v in namespace.items():

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkBase.py in LoadModule(name, namespace)
     81         deps = sorted(data['depends'])
     82         for dep in deps:
---> 83             LoadModule(dep, namespace)
     84 
     85     if itkConfig.ImportCallback:

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkBase.py in LoadModule(name, namespace)
     91     loader = LibraryLoader()
     92     if not swigModuleName in sys.modules:
---> 93         module = loader.load(swigModuleName)
     94 
     95     # OK, now the modules on which this one depends are loaded and

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itkBase.py in load(self, name)
    209         self.setup()
    210         try:
--> 211             return importlib.import_module(name)
    212         finally:
    213             self.cleanup()

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap_external.py in exec_module(self, module)

C:\ProgramData\Anaconda3\envs\registration\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itk\Configuration\..\ITKPyBasePython.py in <module>
     13     from . import _ITKPyBasePython
     14 else:
---> 15     import _ITKPyBasePython
     16 
     17 try:

ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

**Comment by thewtex** [comment]
@paulomontijo thanks for the investigation. Does the error persist in a fresh conda environment?

**Comment by paulomontijo** [comment]
@thewtex,

yes, the error persists in both the conda base environment and in a fresh conda environment.

**Comment by thewtex** [comment]
@paulomontijo what is the version of Python, e.g. 3.8?

**Comment by paulomontijo** [comment]
@thewtex,

I'm using python 3.6.0 anaconda 4.3.1 (64 bits)

**Comment by paulomontijo** [comment]
Any updates on this issue?

**Comment by paulomontijo** [comment]
Hello @thewtex,

the problem still persists when I try to use compare after using pip install --upgrade itkwidgtes (version 0.27.5) in a fresh conda environment.

```
C:\ProgramData\Anaconda3\envs\registration\lib\site-packages\itk\Configuration\..\ITKPyBasePython.py in <module>
     13     from . import _ITKPyBasePython
     14 else:
---> 15     import _ITKPyBasePython
     16 
     17 try:

ImportError: DLL load failed: The specified module was not found
```.

**Comment by thewtex** [comment]
@paulomontijo please try:

```
python -m pip install --upgrade itk itk-meshtopolydata
```
and let us know how it goes.

**Comment by paulomontijo** [comment]
@thewtex,

it worked! Thanks for the help and the patience :)
