### ISSUE TITLE
Multiple point sets, geometries

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itkwidgets#307]
With the performance enhancements added in 0.27.0, when an image + geometry or point sets or multiple point sets or geometries are added to a viewer, the widget does not display.

More information:

https://discourse.itk.org/t/itkwidget-displaying-multiple-objects-at-once/3090

**Comment by qianyizhang** [comment]
any updates? I was playing around with multiple point_sets and it was fine until I upgraded my enviroment...

**Comment by thewtex** [comment]
This is addressed by #311 -- after CI testing passes, will merge and release in 0.27.5.
