### ISSUE TITLE
itkwidget view not working in Jupyter Notebook

### ISSUE THREAD

**Issue by AaronV77** [InsightSoftwareConsortium/itkwidgets#310]
Hello! I'm trying to run one of the given examples: https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/3DImage.ipynb

and the view() function at the end of the notebook is not showing anything. I'm using an Anaconda environment that is using Jupyter Notebook. Do I need to be using Jupyter Lab for these examples or is there some configuration that I am missing for Jupyter Notebook? Thanks for any help!

**Comment by thewtex** [comment]
Hello @AaronV77 !

These examples also work with the Jupyter Notebook.

Are there more details on:

- The operating system
- The Python version
- The itkwidgets version

?

**Comment by AaronV77** [comment]
For sure! I just didn't know if it would be something simple.
The following:
- OS: Centos 8
- Python: 3.7.6
- itkwidgets: 0.27.4
- Jupyter: 1.0.0
- Jupyter-Client: 6.1.3

Let me know if you need anything else! Thanks

**Comment by thewtex** [comment]
Please try itkwidgets 0.27.5 and let us know how it goes.

**Comment by AaronV77** [comment]
@thewtex I will give it a try today and report back!

**Comment by AaronV77** [comment]
My apologies for not doing what I said, but I have finally gotten to updating the package to 0.29.0 and everything is working as anticipated. Thanks for your timely response / bug correction, and have a great evening / weekend!

**Comment by thewtex** [comment]
@AaronV77 wonderful, thanks for the follow-up!

**Comment by Interesting6** [comment]
same issure

- OS: Ubuntu 18.04.5 LTS
- Python: 3.6.7
- itkwidgets: 0.23.1,  0.29.0, 0.32.1,  all of these are same -- no output.
- Jupyter: 1.0.0
- Jupyter-Client: 6.2.0

help.
