### ISSUE TITLE
X/Y/Z anisotropic voxel scaling possible with the itkwidgets.view function?

### ISSUE THREAD

**Issue by haesleinhuepf** [InsightSoftwareConsortium/itkwidgets#335]
Hi all, hi @thewtex ,

I'm just trying to setup a short intro to working with 3D image data and I was playing with `itkwidgets.view`. My data is usually anisotropic. Thus, I was wondering if it's possible to specify voxel size? Furthermore, I couldn't find the online documentation of the `view` method. That's my simple code snippet:

```
from itkwidgets import view

view(image)
```

My example data is stored [here](https://git.mpi-cbg.de/rhaase/lecture_applied_bioimage_analysis_2020/blob/master/12_Volumetric_image_data/data/000200.raw.tif) and it looks flat in the itk viewer ;-)

![image](https://user-images.githubusercontent.com/12660498/85195729-45613c80-b2d5-11ea-939d-abf86e241d3d.png)

Thanks for your support!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Voxel size is supposed to be 0.52x0.52x1.98 micron.... How can I enter it? (-:

**Comment by thewtex** [comment]
Hello @haesleinhuepf !

Yes, of course!

Here is a notebook:

https://gist.github.com/thewtex/d5caa6a4b2c2de6bc0e62aebf1206ee7

![AnisotropicSpacing - Jupyter Notebook](https://user-images.githubusercontent.com/25432/85216371-c6f6b000-b351-11ea-93f7-0b2424a91e21.gif)

We generally use an image data structure that supports spacing, e.g. `itk.Image`. We could also add support for the ImageJ image data structure via pyimagej -- are you interested in that?

**Comment by haesleinhuepf** [comment]
Hey Matt @thewtex ,

awesome, thanks! Exactly what I was looking for!

> We could also add support for the ImageJ image data structure via pyimagej

No need for that, but thanks. I think if we're all compatible to numpy, it should be fine and prevents unnecessary code.

Thanks again and have a great weekend! :-)

Cheers,
Robert
