### ISSUE TITLE
Unexpected behavior on CROP button in the widget user interface

### ISSUE THREAD

**Issue by dani-lbnl** [InsightSoftwareConsortium/itkwidgets#361]
Adjust the location of the **region of interest** (roi) by click and dragging the corner of the cropping box
- Works: VISUALLY if there are no secondary adjustments
- Doesnt work : if you want to access selected region neither using viewer.roi_slice() or viewer.roi_region()

Version: 
- My itk version is: 5.1
- My itkwidget version is: 0.31.3

OS: tested on 2 systems:
- Mac OS High Sierra
- SUSE Linux:
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"

**Comment by thewtex** [comment]
@dani-lbnl thanks for the report :-)

Addressed in #362
