### ISSUE TITLE
Error using ConnectedComponentImageFilter on complex scientific images

### ISSUE THREAD

**Issue by dani-lbnl** [InsightSoftwareConsortium/itkwidgets#366]
Page: 
https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/LabelImages.ipynb

Error:
RuntimeError: /Users/kitware/Dashboards/ITK/ITKPythonPackage/ITK-source/ITK/Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx:145:
itk::ERROR: itk::ERROR: ConnectedComponentImageFilter(0x7fbd5a7ac420): Number of objects (1195) greater than maximum of output pixel type (255).

**Comment by thewtex** [comment]
@dani-lbnl thanks for the report :+1: .

This will be addressed by: https://github.com/InsightSoftwareConsortium/ITK/pull/1938

**Comment by thewtex** [comment]
This is addressed in the `itk-5.1.1` Python package, available via pip, soon to be available in conda.
