### ISSUE TITLE
does point_sets has limit on number of items?

### ISSUE THREAD

**Issue by qianyizhang** [InsightSoftwareConsortium/itkwidgets#367]
the view widget gets stuck when loading a list/dict with ~10 point sets, but works fine when I concatenate them into 1 list.

Furthermore, if I first initialize the view with some points to get it started, then setting view.point_sets to the list of point sets I wish to display, it works just fine.

**Comment by thewtex** [comment]
@qianyizhang thanks for the report.

Could you please share a simple notebook / GitHub Gist that reproduces the behavior?

**Comment by qianyizhang** [comment]
```python
from itkwidgets import view
import numpy as np

def get_pts_list(pts_num = 1000, list_num = 20):
    stride = pts_num//list_num
    pts = np.random.random((pts_num,3))
    pts_list = [pts[i*stride:(i+1)*stride] for i in range(list_num)]
    return pts_list

pts_list = get_pts_list(5000, 5) # this works just fine
view(point_sets = pts_list)
pts_list = get_pts_list(100, 10) # this stucks from time to time
view(point_sets = pts_list)
pts_list = get_pts_list(100, 20) # this never shows anything
view(point_sets = pts_list)

**Comment by thewtex** [comment]
@qianyizhang thank you for the nice example! I was able to reproduce and address the issue. A patch is forthcoming. This will be addressed in the next release.
