### ISSUE TITLE
itkwidgets fails silently 

### ISSUE THREAD

**Issue by VolkerH** [InsightSoftwareConsortium/itkwidgets#379]
Hi,
I just installed itkwidgets and tried to view an volume on a browser on a Windows remote desktop.
Unforunately it is failing silently. I suspect a lack of WebGL support (the remote desktop only supports
a very old version of OpenGL), but when looking for existing issues on this  I noticed that I actually 
 already raised an issue about the lack of error message when WebGL and it had been addresses in #41 .

This is what I am experiencing:
 
![image](https://user-images.githubusercontent.com/2210044/90012725-4b790580-dce7-11ea-95c7-e9903e63308b.png)

That is, I try and display an array but the viewer widget does not show up and does not report an error in the notebook (nor on the console from which the notebook server was started).

My assumption is that the fix for #41 only detects whether the browser is WebGL compatible but cannot determine whether a supported version of OpenGL is present on the system. 

I am just putting the issue here for others to find, I doubt that this is critical for many users.  Also, I'm not sure whether this is something to fix in itkwidgets or whether the web  browser should actually display an error message.

**Comment by thewtex** [comment]
Hi, @VolkerH thanks for the report.

We have support for WebGL 2, and partial support for WebGL 1, but we can only go by what the browser tells us (the browser will not be aware that it is running in remote desktop). However, this may be a different issue.

Are you using JupyterLab or the Jupyter Notebook? What is the Jupyter version?

More information may be available in the browser debugger Console, usually accessed with Control + Shift + I.

**Comment by VolkerH** [comment]
Ok, I tried to look at the browser debugger console. But this time round the viewer appeared (same browser, same jupyter version, same kind of np-array). 

I have a hunch what might have happened. The notebook where it failed was using a tensorflow model and that probably used up so much GPU memory that there was not enough left for WebGL.

Probably safe to close this.

**Comment by thewtex** [comment]
@VolkerH thanks for the update!
