### ISSUE TITLE
VTK Data Type 12 not supported

### ISSUE THREAD

**Issue by akaszynski** [InsightSoftwareConsortium/itkwidgets#391]
In your `_vtk_data_type_to_vtkjs_type`, it appears that VTK data type 12 (VTK_ID_TYPE) isn't supported.  You can just map this type to a `Int32Array` for vtkjs.

**Comment by thewtex** [comment]
@akaszynski good catch. Could you please create a PR?

**Comment by akaszynski** [comment]
Glady, please see #393
