### ISSUE TITLE
issue rendering 2D vtk image

### ISSUE THREAD

**Issue by zivy** [InsightSoftwareConsortium/itkwidgets#401]
itkwidgets 0.32.0 on OSX catalina, issues displaying [image](https://data.kitware.com/api/v1/file/57b5d9ef8d777f10f269538f/download/cthead1.png) used by the 2D display notebook example (both code blocks work when I tried a [3D image](https://data.kitware.com/api/v1/file/57b5ddb28d777f10f2695f97/download/training_001_ct.mha)) 

1. This code works
```
import itk
from itkwidgets import view

view(itk.imread('cthead1.png'))
```
2. This doesn't (nothing displayed, no error issued)
```
import vtk
from itkwidgets import view

reader = vtk.vtkPNGReader()
reader.SetFileName('cthead1.png')
reader.Update()
view(reader.GetOutput())
```

**Comment by dave3d** [comment]
It's using the MetaImageReader to read a PNG image?

**Comment by zivy** [comment]
Good catch, don't know how I missed that as I was playing with different images. In any case using the `vtkPNGReader` (I updated the code snippet) didn't change anything. Did it work for you with the correct reader?

**Comment by dave3d** [comment]
It looks like there are some VTK rendering issues going on.  The image object is in the scene, for me, but it's really noisy and faint or invisible depending on the viewing angle.

**Comment by dave3d** [comment]
https://github.com/InsightSoftwareConsortium/itkwidgets/pull/402
Fixed it.  My 2nd commit checks for a zdim==1.  In that case set up the dims, spacing & origin as 2d arrays.

**Comment by zubair-ahmed-ai** [comment]
```
import itk
from itkwidgets import view

view(itk.imread('cthead1.png'))
```

This code doesn't do anything for me, nothing is displayed

**Comment by zivy** [comment]
Hello @zubair-ahmed-ai,

I believe the itkwidgets don't display color images, only single channel that are colormapped (not 100% sure though).

**Comment by thewtex** [comment]
Closing this since #402 should have addressed it.

@zubair-ahmed-ai please try using itkwidgets 0.32.1. itkwidgets does support color RGB images. If issues are observed, please open another issue.
