### ISSUE TITLE
no volume is shown 

### ISSUE THREAD

**Issue by SummerZ2020** [InsightSoftwareConsortium/itkwidgets#406]
here is the code i run with itkwidgets, I am wondering show the volume with itkwidgets.view.
`from itkwidgets import view 
import itkwidgets 
import nibabel as nib 
nii = nib.load('1.2.840.113704.9.1000.16.0.20140917113208887_00030004.nii.gz') 
img = nii.get_data() 
viewer = view(img,cmap=itkwidgets.cm.grayscale) 
viewer`
But there is not any response after this code running. nothing pop up seems nothing happened.
there is an error in the itkwidgets installation:"ERROR: itk-meshtopolydata 0.6.5 has requirement itk-core>=5.2rc03, but you'll have itk-core 5.1.2 which is incompatible.
ERROR: ipympl 0.7.0 has requirement ipywidgets>=7.6.0, but you'll have ipywidgets 7.5.1 which is incompatible." 
So i tried to uninstall itk-core 5.1.2 and then install itk-core5.2rc03. but there is an error which is "ModuleNotFoundError: No module named 'itkHelpers'". what can i do if i want to show the volume with itkwidgets.view. Thank you in advance.

**Comment by thewtex** [comment]
@SummerZ2020 thanks for the report!

Addressed in #409 #420
