### ISSUE TITLE
Custom Matplotlib ColorMap for images  not working

### ISSUE THREAD

**Issue by OmarRH12** [InsightSoftwareConsortium/itkwidgets#412]
Hi, wonderful package for visualization!

I am running into an issue. I try to use a custom color map but the cmap argument doesn't accept it. I created a custom  LinearSegmentedColormap and a Nx3 numpy array with the RGB succession. None of them worked.

I went to the examples, and tried itkwidgets/examples/SpecifyAColormap.ipynb

I get the same mistake when running

`viewer.cmap = 'gist_earth'`

or

`colormap = np.array([[0.0, 0.0, 0.0],
                     [1.0, 1.0, 1.0]])
viewer.cmap = colormap`

I get: 
TraitError: The 'cmap' trait of a Viewer instance must be a list or None, but a value of class 'str' (i.e. 'gist_earth') was specified.

This error seems to be fixed for 'gist_earth' when we set it as a list

`viewer.cmap = ['gist_earth']`

But that doesnt work for the custom colormap, trying this:

`colormap = np.array([[0.0, 0.0, 0.0],
                     [1.0, 1.0, 1.0]])
viewer.cmap = [colormap]`

Gives the following message:

ValueError: Can't clean for JSON: array([[0., 0., 0.],
       [1., 1., 1.]])

As I said before I have tried making LinearSegmentedColormap but I get the same mistake making reference that it can't clean for JSON.

I am wondering if this is a known issue and if there is a workaround.

Kind regards!

Omar

**Comment by thewtex** [comment]
Hello Omar!

Thank you for the kind words and report!

This issue has been addressed in https://github.com/InsightSoftwareConsortium/itkwidgets/commit/09ee4a174c87613dc53fb51789788f286c50a39f

Note that the syntax has been updated there to require the use of a list after updates to library dependencies. There was a fix to address the `LinearSegmentedColormap` issue also.

Best,
Matt

**Comment by OmarRH12** [comment]
Thank you Matt! Very well appreciated!
Cheers! 

Omar
