### ISSUE TITLE
`viewer.get_region()` does not update after selecting ROI on volume viewer

### ISSUE THREAD

**Issue by stefsmeets** [InsightSoftwareConsortium/itkwidgets#424]
Hi all! I'm trying to use the `Select ROI` function in `itkwidgets.view` which would be very useful for one of my projects. However, the state does not seem to get updated on the viewer object, i.e. `viewer.roi` or `viewer.get_region()` does not update after I change the ROI on the widget. It seems to always give me the shape of the entire volume.

I then tried with the notebook in the examples, which has the same issue for me.

This is using `itkwidgets 0.32.1` on Windows 10.

Any idea what is going on?

**Comment by ezatterin** [comment]
Same problem here, running `itkwidgets 0.32.2` and Ubuntu `20.04`.

**Comment by thewtex** [comment]
Hi, we now have support in itkwidgets 1.0a42:

https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/integrations/itk/SelectROI.ipynb
