### ISSUE TITLE
Cannot use pip to install latest version of itkwidgets

### ISSUE THREAD

**Issue by mikami520** [InsightSoftwareConsortium/itkwidgets#440]
When I try to use "pip install itkwidgets" on terminal, it works with version 0.19.0. However, the latest version is 0.32.1. Then I tried another way 'pip install itkwidgets==0.32.1", it gives me error that 
"ERROR: Could not find a version that satisfies the requirement itk-meshtopolydata>=0.7.1 (from itkwidgets) (from versions: none)
ERROR: No matching distribution found for itk-meshtopolydata>=0.7.1"

But when I checked and installed the itk-meshtopolydata, I cannot installed successfully and pip said the version is None. Could anyone help me with this issue?

**Comment by marcmorcos** [comment]
what version of python?

**Comment by francesco-ballarin** [comment]
Fairly sure it is python 3.10. I have opened https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/issues/45

**Comment by thewtex** [comment]
3.10, 3.11 supported added in 0.33.4
