### ISSUE TITLE
support for meshes on main

### ISSUE THREAD

**Issue by francesco-ballarin** [InsightSoftwareConsortium/itkwidgets#490]
Hi,
I am using `itkwidgets<1.0` to visualize finite element meshes (sometimes 2D, sometimes 3D) and fields defined on them, often through `pyvista`.

`itkwidgets` goal on `master` branch is stated as

> Interactive Jupyter widgets to visualize images, point sets, and meshes on the web.

while on the `main` branch it is

> Interactive widgets to visualize images, point sets, and 3D geometry on the web.

with no mention of "meshes".

With this I would like to ask if users can expect support for meshes to be added back to `main` at some point in future, or if that is not something you are interested in anymore.

Thanks,
Francesco

**Comment by PaulHax** [comment]
Hello Francesco!  
Meshes are still supported on `main`.  If you find something something unexpected in your tests, please let us know.

**Comment by francesco-ballarin** [comment]
Thanks, then I must be confused by the documentation on `main`.

On `master`, I used to pass the `geometries` kwarg to `itkwidgets.view`, see
https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/itkwidgets/widget_viewer.py#L965

I find no mention for it on `main`, see
https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/itkwidgets/viewer.py#L217

**Comment by bnmajor** [comment]
@francesco-ballarin I am sorry for the confusion but you are correct, there is not support for geometries on `main` at this point in time. We absolutely intend to add support for geometries again, but at this point there is some additional work that needs to be done before that can be supported again with this newer version of itkwidgets. In the meantime though the `master` branch does still have this support.

**Comment by francesco-ballarin** [comment]
Thanks @bnmajor for the clarification! Good to know that such support will be added at some point, I'll make sure to come back and test it  when it will land on `main` (and then close this issue).

**Comment by PaulHax** [comment]
Would be nice if we can update geometries after first load: https://discourse.itk.org/t/adding-additional-geometries-to-viewer-changes-colours-of-outputs/5449/3

**Comment by francesco-ballarin** [comment]
My main motivation was using `itkwidgets` within `pyvista`. Since the `itkwidgets` backend was removed from `pyvista` in https://github.com/pyvista/pyvista/pull/3737, I don't have any further interest in this, hence I am closing this. Feel free to reopen if someone else is interested in this for `itkwidgets` on its own, rather than within `pyvista`.

**Comment by mgenet** [comment]
Hello,
I am very much interested in the support for meshes in itkwidgets. Can we keep this open?
