### ISSUE TITLE
Support for py39 and above

### ISSUE THREAD

**Issue by brey** [InsightSoftwareConsortium/itkwidgets#510]
I have an issue open on the [conda forge feedstock](https://github.com/conda-forge/itkwidgets-feedstock/issues/50) but I had no answer so I thought to raise it here as well. 

Currently we are using `itkwidgets` in our package as `conda` upstream dependency which creates a constraint to keep it at `py38`. Is there a reason that the package isn't build for `py39` and above?

**Comment by thewtex** [comment]
Hi, 0.X works with `py39`. It should work with `py310` soon. 1.X alpha works with `py38` and above.

**Comment by brey** [comment]
@thewtex thanks for the update.

Will it be possible to update  the `conda-forge` package to support at least 3.9? Based on  #531 you could do 3.7,3.8,3.9 in the CI/CD there.

**Comment by thewtex** [comment]
The conda-forge builds look like they are failing due to a missing requirements.txt -- an attempt to address this with https://github.com/InsightSoftwareConsortium/itkwidgets/pull/539.

**Comment by gselzer** [comment]
The pyimagej team just ran into this issue today. Has there been any progress on this?

**Comment by thewtex** [comment]
Hi @gselzer we'll release a new patch version with #539 along with itk-5.3.0 including support for CPython 3.9, 3.10, 3.11 in about a week's timeframe.

**Comment by gselzer** [comment]
Great, thanks @thewtex!

**Comment by thewtex** [comment]
Related side-note, we also have PyImageJ notebooks testing / passing on the 1.X branch with #575 .

**Comment by thewtex** [comment]
Python 3.9, 3.10, 3.11 added 0.32.4
