### ISSUE TITLE
mode / view_mode inefficient

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/itkwidgets#517]
Using the latest pre-release (using jupyer notebooks on Linux Python 3.9), passing `mode='x'` or `view_mode='x'` (idem for y / z) as parameter to itkwidgets.view does not change the display mode, one still has the 3D view. Pressing the corresponding buttons on the user interface does work.

**Comment by thewtex** [comment]
@SimonRit thanks for the report.

We are working on addressing this via #515 #466

**Comment by SimonRit** [comment]
Excellent, thanks! Sorry I did not make the connection...

**Comment by bnmajor** [comment]
The syntax has changed slightly for the pre-release channel (which is what we recommend using).
```
view(..., view_mode='x') -> view(..., view_mode='XPlane')
```
with the options of `XPlane`, `YPlane`, `ZPlane`, or `Volume` (the default is `Volume`).
