### ISSUE TITLE
Pin itk-vtk-viewer and itk-viewer-bootstrap-ui versions

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itkwidgets#518]
itkwidgets points to the latest version of itk-vtk-viewer, itk-viewer-bootstrap-ui, and itk-viewer-material-ui
- `https://kitware.github.io/itk-vtk-viewer/app`  
- `https://cdn.jsdelivr.net/npm/itk-viewer-bootstrap-ui@0/dist/bootstrapUIMachineOptions.js.es.js`

These version can get out of sync: I changed the naming on a variable in the XState context in itk-vtk-viewer. That broke the Bootstrap-UI code.

Would be good to pin the full versions we point to in the CDNs.

**Comment by thewtex** [comment]
Closed via #523
