### ISSUE TITLE
Unable to visualize unstructured grid

### ISSUE THREAD

**Issue by wonderfuloceans** [InsightSoftwareConsortium/itkwidgets#520]
I am trying to visualize an unstructured grid. I read the data with this code: 
```
import vtk
from itkwidgets import view

filename = '../drugivtk.vtk'

reader = vtk.vtkUnstructuredGridReader()
reader.SetFileName(filename)
reader.Update()
grid = reader.GetOutput()

view(geometries = grid)
```

However, when trying to pass the data to `view()`, it displays nothing, as shown here: 

![image](https://user-images.githubusercontent.com/98784119/189221793-29114e2d-b037-442f-bfd9-0d4f2db1f3e8.png)

After opening the browser console I get this error: 

![Screenshot from 2022-09-08 22-33-47](https://user-images.githubusercontent.com/98784119/189222442-579c9a14-03d3-48c7-997b-3eaf1b17d1c5.png)

Therefore I tried running some examples. After running [this example of polydata point sets](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/integrations/vtk/vtkPolyDataPointSet.ipynb) as well as [this example of numpy array point set](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/NumPyArrayPointSet.ipynb) the `view()` function works normally. However, [this example of displaying unstructured grids](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/vtkUnstructuredGrid.ipynb) does not display anything and shows the same browser error as the code above. 

I have Python 3.10.4. Version of itkwidgets is 1.0a9. Version of JupyterLab 3.4.5. The vtk file in the code above: [drugivtk.zip](https://github.com/InsightSoftwareConsortium/itkwidgets/files/9530768/drugivtk.zip). In addition, the file displays normally in Paraview.

**Comment by bnmajor** [comment]
Hi @wonderfuloceans! Unfortunately at this point the pre-release does not yet support geometries, however the main release (v0.32.2) still does.

**Comment by mgenet** [comment]
Hello,
Any update in this? Thank you!
