### ISSUE TITLE
2D viewer support

### ISSUE THREAD

**Issue by fedorov** [InsightSoftwareConsortium/itkwidgets#572]
I think it would be very helpful to have a widget that would support 2d view of the image + label overlay (ie an equivalent to 2d slice views in 3D Slicer). I think for many practical purposes of viewing image segmentation results, current 3d widget is not sufficient for evaluating the results. 

Perhaps this is something that is already possible, but I could not find the answer in the [documentation](https://itkwidgets.readthedocs.io/en/latest/). I looked over the open issues and didn't find one that has a similar request. Sorry if I missed it.

**Comment by PaulHax** [comment]
There are some boxy buttons hidden away behind the "menu" button that change the "view mode."

![image](https://user-images.githubusercontent.com/16823231/199559623-465472a4-0e87-489b-b8ce-ef6d99a98b4e.png)

Should also be able to control with Python.
```
viewer = view(image)
viewer.set_view_mode('ZPlane') # or 'XPlane' or 'YPlane' or 'Volume'
```

**Comment by fedorov** [comment]
Thank you for pointing this out - I missed that UI feature...
