### ISSUE TITLE
Slice value-under-cursor display is hidden by slice slider

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/itkwidgets#576]
![image](https://user-images.githubusercontent.com/279727/200883857-9fca156c-a16b-4534-97f8-addec9e3d596.png)

**Comment by thewtex** [comment]
CC @PaulHax

**Comment by thewtex** [comment]
@aylward great points!

I created these sub-issues:

- https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/issues/127
- https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/issues/126

**Comment by thewtex** [comment]
@bnmajor could you please bump the viewer, ui, and cut a release?
