### ISSUE TITLE
Point set and image are displayed out of correspondence in `0.32.5`

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/itkwidgets#596]
## Overview

I am trying to view a small point set and image in the same scene. The points in the point set all fall within the extent of the image, but they are displayed as being out of correspondence.

![points-outside-extent](https://user-images.githubusercontent.com/40648863/211105501-3f3be02b-b92a-4756-bcc2-26d31fb901d7.png)

## Platform

Windows 10
Python 3.8.5

## Version

`itkwidgets==0.32.5`

## Details

The image is of type `itk.itkImagePython.itkImageF3` and extends from `[0,0,0]` to `[-11.4, 13.2, -8]` in physical space. The full image printout is as follows:

```
Image (0000014AAAD1BE70)
  RTTI typeinfo:   class itk::Image<float,3>
  Reference Count: 1
  Modified Time: 651
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 607
  UpdateMTime: 648
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1320, 800, 1140]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1320, 800, 1140]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [1320, 800, 1140]
  Spacing: [0.01, 0.01, 0.01]
  Origin: [0, 0, 0]
  Direction: 
-0 0 -1
1 -0 0
0 -1 0

  IndexToPointMatrix: 
0 0 -0.01
0.01 0 0
0 -0.01 0

  PointToIndexMatrix: 
0 100 0
0 0 -100
-100 0 0

  Inverse Direction: 
0 1 0
0 0 -1
-1 0 0

  PixelContainer: 
    ImportImageContainer (0000014AAAEB5C30)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,float>
      Reference Count: 6
      Modified Time: 644
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0000014DCB245040
      Container manages memory: true
      Size: 1203840000
      Capacity: 1203840000

```

The list of points is as follows:
```
itkPointF3 ([-7.92542, 1.37847, -5.17248])
itkPointF3 ([-9.26167, 1.89344, -5.11759])
itkPointF3 ([-10.2177, 3.22767, -4.78993])
itkPointF3 ([-10.375, 4.59346, -4.45223])
itkPointF3 ([-10.0854, 5.16987, -4.3125])
itkPointF3 ([-9.69685, 5.01715, -4.34024])
itkPointF3 ([-9.4274, 4.36813, -4.49985])
itkPointF3 ([-8.87071, 3.6622, -4.6875])
itkPointF3 ([-7.96137, 3.36249, -4.76475])
itkPointF3 ([-7.93358, 3.30732, -4.77887])
```

## Additional Notes

From viewing the scene with the grid enabled it seems that the point set is correctly physically located and the image is not. Perhaps something to do with the direction matrix?

![point-outside-extent-with-grid](https://user-images.githubusercontent.com/40648863/211106084-0e595ae9-75b3-491b-afa1-f46653af67d0.png)

**Comment by aylward** [comment]
To me the plot seems right.  Along the x axis, the points are near -7.
 For the image, the origin is 0,0,0 and the x direction is positive in the
x axis (the second direction vector) and extends to about 8 (dimsize is 800
in index space).  Could you send me that image, and I will verify using
Image viewer?

S

**Comment by tbirdso** [comment]
Hi @aylward , thanks for taking a look. The image is publicly accessible and can be found here: [`average_template_25.nii.gz`](http://download.alleninstitute.org/informatics-archive/converted_mouse_ccf/average_template/average_template_25.nii.gz).

In the issue description here I determined the extent by getting the physical points at the two farthest image indices:
```
> image.TransformIndexToPhysicalPoint([0,0,0])
itkPointD3 ([0, 0, 0])
> image.TransformIndexToPhysicalPoint(itk.size(image))
itkPointD3 ([-11.4, 13.2, -8])
```

As you've noted, this disagrees with the apparent extent of `[0,0,0] -> [+7, -11, -13]` displayed in itkwidgets.

**Comment by tbirdso** [comment]
@aylward It looks like your image may not have uploaded correctly?

**Comment by aylward** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/279727/211373681-d2737750-6aab-4818-ab1c-7212b084fa78.png">

**Comment by tbirdso** [comment]
From further testing it seems that an image is correctly oriented when the direction matrix has nonzero elements only along the diagonal. Perhaps an issue with column-major versus row-major interpretation of the direction matrix?
