### ISSUE TITLE
JupyterLite Hello3DWorld

### ISSUE THREAD

**Issue by scrgiorgio** [InsightSoftwareConsortium/itkwidgets#617]
If I open:

https://itkwidgets.readthedocs.io/en/latest/_static/retro/notebooks/?path=Hello3DWorld.ipynb

and "run" the first cell, I am getting:

```
ValueError: Can't find a pure Python 3 wheel for 'itkwidgets==1.0a18'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```

(tried to change `itkwidgets` to some other version, but same error or missing pure python dep e.g. `ngff-zarr[dask-image]>=0.1.6`).
Is there a configuration/simple Jupyter Notebook I can run on:

https://jupyterlite.github.io/demo/lab/index.html

? Thanks

**Comment by thewtex** [comment]
Hi,

Thanks for the report!

This was addressed with #628 -- make sure to reload your browser cache to get the update.
