### ISSUE TITLE
Get position/coordinate of user click

### ISSUE THREAD

**Issue by cwmok** [InsightSoftwareConsortium/itkwidgets#667]
Hi @thewtex,

I would like to get the position/(x, y, z)-coordinate of the user click action. I come across a similar issue in  https://github.com/InsightSoftwareConsortium/itkwidgets/issues/388, but it seems that it is not yet implemented. Could you advise on that issue? What are the alternative ways to get the position/(x, y, z)-coordinate of the current view or click from `viewer`?

Thanks for your nice work, and thank you in advance. 

Tony

**Comment by thewtex** [comment]
Hi Tony,

Thanks for the report / request!

We are refactoring to add the functionality as detailed in #388.

**Comment by cwmok** [comment]
Great! I look forward to the new functionality of itkwidgets!
