### ISSUE TITLE
kernel of DigitalSubtractionAngiographyVesselPath.ipynb dies for different path points

### ISSUE THREAD

**Issue by IsabellaPa** [InsightSoftwareConsortium/itkwidgets#672]
Hello,
I was playing around with the DigitalSubtractionAngiographyVesselPath.ipynb example and noticed that if I change the path file to other points, a lot of times the kernel dies at the last view function (view(dsa, geometries=path, ui_collapsed=True)).
When I use my own image, which is smaller, I am completely unable to find a combination of points that works.
I moved the code to VS Code in hope that I would get an error message but the script just stops executing in the view function after the viewer is initialized.

Here are some examples of paths that failed for me: 
Path: [394.00, 203.00] [0.00, 0.00]
Path: [394.00, 203.00] [1.00, 20.00]
Path: [394.00, 203.00] [001.00, 020.00]
Path: [94.00, 203.00] [60.00, 230.00] [250.00, 190.00]
Path: [204.00, 23.00] [120.00, 80.00] [273.00, 19.00] [94.00, 173.00] [394.00, 121.00] [403.00, 237.00]

The original path in the example works fine, so I don't think that it is a setup problem. 
Can I debug this somehow, are there restrictions for possible points or is this a bug?
Cheers :)

**Comment by bnmajor** [comment]
Hi @IsabellaPa! Can you point me to this `DigitalSubtractionAngiographyVesselPath.ipynb` example? And can I ask which version of itkwidgets you are using?

**Comment by bnmajor** [comment]
@IsabellaPa Thanks for the information! I took a quick look at the notebook and FWIW I don't believe there is an issue with the visualization (itkwidgets) but rather in the paths that you are building (for example I was getting `0` back for `path.GetVertexList().Size()`). It seems like this is a question better suited for the [ITKMinimalPathExtraction](https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/issues) repo. Please let me know if I am misunderstanding your question though!
