### ISSUE TITLE
Compatibility Jupyter Notebook 7 and itkwidgets

### ISSUE THREAD

**Issue by gegelagaffe** [InsightSoftwareConsortium/itkwidgets#680]
I tried to install itkwidgets on Notebook 7 but it failed. Is there a way to do it ?

**Comment by thewtex** [comment]
Will required https://github.com/imjoy-team/imjoy-jupyterlab-extension/issues/2

**Comment by thewtex** [comment]
Addressed with #741

**Comment by thewtex** [comment]
Should be [addressed with itkwidgets v1.0a50](https://github.com/InsightSoftwareConsortium/itkwidgets/releases/tag/v1.0a50). If not, please re-open. Thanks!
