### ISSUE TITLE
vmin and vmax viewer properties set color range

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itkwidgets#723]
I don't know how to wrap get/set of color range with matplotlib like vmin and vmax properties.  How to do synchronous wrapping of async Viewer methods?

Goal is something like adding this to Viewer class
```
    @property
    def vmin(self):
        range = self.get_image_color_range()
        return range[0]
    @vmin.setter
    def vmin(self, vmin):
        range = self.get_image_color_range()
        range[0] = vmin
        self.set_image_color_range(range)
```

**Comment by bnmajor** [comment]
Nice! The synchronous wrapping is added with the `@fetch_value` decorator, and you'll need to make make anything awaiting a network request async:
```
    @property
    @fetch_value
    async def vmin(self):
        range = await self.get_image_color_range()
        return range[0]
    @vmin.setter
    @fetch_value
    async def vmin(self, vmin):
        range = await self.get_image_color_range()
        range[0] = value
        self.set_image_color_range(range)
```

And just a reminder that if you're providing an example we need to resolve anything requiring a network request in the next cell ([for now](https://itkwidgets.readthedocs.io/en/latest/advanced.html#returning-values) at least):
```
viewer.vmin = 10
```
```
vmin = viewer.vmin
```
``` 
vmin
```
