### ISSUE TITLE
Add a example that demonstrates how to select channels from a multi-channel image

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itkwidgets#85]
xref #74, demonstrate with @vianamp 's data: https://www.dropbox.com/s/us4s3012ndo6lj3/yeast_mito.tif?dl=0

**Comment by thewtex** [comment]
Trait should be `channels` as discussed in #74.

**Comment by thewtex** [comment]
@jourdain @martinken a good multi channel volume for testing is linked above

**Comment by jourdain** [comment]
I get a 404 on the link above.

**Comment by thewtex** [comment]
@jourdain here is a truncated version, converted to NRRD:

  https://data.kitware.com/api/v1/file/5bbac5988d777f06b917b66e/download

**Comment by thewtex** [comment]
#329 adds the `channels` trait.

We have an example in https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/VolumeOpacityTransferFunction.ipynb
